// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4XdyG7gGEI2lQyZEZ0w34cu3E-G91MYc',
    appId: '1:513816891063:android:8d1dcc68430db0b294c732',
    messagingSenderId: '513816891063',
    projectId: 'grofery-a5e02',
    storageBucket: 'grofery-a5e02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfWtrjotI7x-iXxzMJaEHBwNMuQb-mTNI',
    appId: '1:710283966065:ios:0b07ddd4691b1c7ccbcdd0',
    messagingSenderId: '710283966065',
    projectId: 'grofery-user',
    storageBucket: 'grofery-user.firebasestorage.app',
    iosBundleId: 'com.axolotls.merawalashopuser',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTdBMmaQyafJNmd5DeT3NkZIGZc90-nw',
    appId: '1:710283966065:web:d034870c169dee11cbcdd0',
    messagingSenderId: '710283966065',
    projectId: 'grofery-user',
    authDomain: 'grofery-user.firebaseapp.com',
    storageBucket: 'grofery-user.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfWtrjotI7x-iXxzMJaEHBwNMuQb-mTNI',
    appId: '1:710283966065:ios:1d922499abb78a35cbcdd0',
    messagingSenderId: '710283966065',
    projectId: 'grofery-user',
    storageBucket: 'grofery-user.firebasestorage.app',
    iosBundleId: 'com.example.hyperLocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvTdBMmaQyafJNmd5DeT3NkZIGZc90-nw',
    appId: '1:710283966065:web:3b0d75ecbf88f932cbcdd0',
    messagingSenderId: '710283966065',
    projectId: 'grofery-user',
    authDomain: 'grofery-user.firebaseapp.com',
    storageBucket: 'grofery-user.firebasestorage.app',
  );

}